# Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: cribr-ns

# ServiceAccount with minimal permissions
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cribr-sa
  namespace: cribr-ns

# Role and RoleBinding for minimal permissions (example: read-only pods in namespace)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cribr-ns
  name: cribr-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cribr-rolebinding
  namespace: cribr-ns
subjects:
  - kind: ServiceAccount
    name: cribr-sa
    namespace: cribr-ns
roleRef:
  kind: Role
  name: cribr-role
  apiGroup: rbac.authorization.k8s.io

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cribr-ns
  name: cribr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cribr-app
  template:
    metadata:
      labels:
        app: cribr-app
      annotations:
        elastic.co/dataset: kubernetes.container_logs.cribr
        elastic.co/namespace: kube-system
        elastic.co/preserve_original_event: "true"
    spec:
      serviceAccountName: cribr-sa
     #automountServiceAccountToken: false   # Uncomment if you want to disable token mounting for pods that don't need API access
      containers:
        - name: cribr-container
          image: 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: cribr-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"

# Service
---
apiVersion: v1
kind: Service
metadata:
  namespace: cribr-ns
  name: cribr-service
spec:
  type: NodePort
  selector:
    app: cribr-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

# Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cribr-ns
  name: cribr-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:493834426110:certificate/8b17e159-e65d-41dc-a83f-f574d6e6b629
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: app.cribr.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cribr-service
                port:
                  number: 3000
