# cribr-deployment-ns-svc-ingress.yaml



# Namespace
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cribr-ns

# cribr-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cribr-ns
  name: cribr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cribr-app
  template:
    metadata:
      labels:
        app: cribr-app
      annotations:
        elastic.co/dataset: kubernetes.container_logs.cribr
        elastic.co/namespace: kube-system
        elastic.co/preserve_original_event: "true"
    spec:
      containers:
        - name: cribr-container
          image: 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: cribr-secrets



# cribr-service-ingress.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: cribr-ns
  name: cribr-service
spec:
  type: NodePort
  selector:
    app: cribr-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP



# cribr-ingress.yaml   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cribr-ns
  name: cribr-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:493834426110:certificate/8b17e159-e65d-41dc-a83f-f574d6e6b629
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: app.cribr.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cribr-service
                port:
                  number: 3000
